# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Fitfind' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Fitfind
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  # pod 'Firebase/Messaging'
  
  target 'FitfindTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
